### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by YBurakD** [IdrisMiles/ElasticImplicitSkinning#1]
Hi,

I encountered the following error when building the source code:

![image](https://user-images.githubusercontent.com/32135008/109008139-05512580-76be-11eb-8dc2-c96fb311fe8e.png)

Here is the text.

> /usr/local/cuda-11.0/bin/nvcc -m64 -arch=sm_50 -c -o cuda_obj/ImplicitSkinGpuWrapper_cuda.o cuda_src/ImplicitSkinGpuWrapper.cu -std=c++14 -ccbin g++ --compiler-options -fno-strict-aliasing --ptxas-options=-v -I/home/ubuntu/ImplicitSkinning/include -I/usr/local/include -I/usr/include -I/usr/local/include/eigen3/ -I/home/idris/dev/include -I/home/idris/dev/eigen/include/eigen3 -I./cuda_inc -I./include -I/include -I/include/cuda
> nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
> In file included from /usr/include/glm/gtx/quaternion.hpp:20:0,
>                  from /usr/include/glm/gtx/vector_angle.hpp:20,
>                  from ./cuda_inc/ImplicitSkinGpuWrapper.h:15,
>                  from cuda_src/ImplicitSkinGpuWrapper.cu:1:
> /usr/include/glm/gtx/norm.hpp:21:3: error: #error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
>  # error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
>    ^~~~~
> In file included from /usr/include/glm/gtx/vector_angle.hpp:20:0,
>                  from ./cuda_inc/ImplicitSkinGpuWrapper.h:15,
>                  from cuda_src/ImplicitSkinGpuWrapper.cu:1:
> /usr/include/glm/gtx/quaternion.hpp:23:3: error: #error "GLM: GLM_GTX_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
>  # error "GLM: GLM_GTX_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
>    ^~~~~
> In file included from /usr/include/glm/gtx/rotate_vector.hpp:18:0,
>                  from /usr/include/glm/gtx/vector_angle.hpp:21,
>                  from ./cuda_inc/ImplicitSkinGpuWrapper.h:15,
>                  from cuda_src/ImplicitSkinGpuWrapper.cu:1:
> /usr/include/glm/gtx/transform.hpp:23:3: error: #error "GLM: GLM_GTX_transform is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
>  # error "GLM: GLM_GTX_transform is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
>    ^~~~~
> In file included from /usr/include/glm/gtx/vector_angle.hpp:21:0,
>                  from ./cuda_inc/ImplicitSkinGpuWrapper.h:15,
>                  from cuda_src/ImplicitSkinGpuWrapper.cu:1:
> /usr/include/glm/gtx/rotate_vector.hpp:21:3: error: #error "GLM: GLM_GTX_rotate_vector is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
>  # error "GLM: GLM_GTX_rotate_vector is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
>    ^~~~~
> In file included from ./cuda_inc/ImplicitSkinGpuWrapper.h:15:0,
>                  from cuda_src/ImplicitSkinGpuWrapper.cu:1:
> /usr/include/glm/gtx/vector_angle.hpp:24:3: error: #error "GLM: GLM_GTX_vector_angle is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
>  # error "GLM: GLM_GTX_vector_angle is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
>    ^~~~~
> Makefile:737: recipe for target 'cuda_obj/ImplicitSkinGpuWrapper_cuda.o' failed
> make: *** [cuda_obj/ImplicitSkinGpuWrapper_cuda.o] Error 1

**Comment by IdrisMiles** [comment]
Hey, I've not touced this code in a long time so a bit rusty on it. But it looks like from the error messages you may need to modify the code a bit, specifically `cuda_inc/ImplicitSkinGpuWrapper.h` to include:
```C++
#define GLM_ENABLE_EXPERIMENTAL
```

**Comment by YBurakD** [comment]
Thank you.  That indeed solved the issue; however, I needed to add that line to all of the header files under cuda_inc.
